name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I'd like CollectionMerger to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... / Another approach could be...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, provide an example of how you'd like to use this feature.
      placeholder: |
        ```csharp
        // Example of how the feature would be used
        var report = collection.MapFrom(...);
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any other relevant information...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Note for contributors**: When implementing this feature, please use [Conventional Commits](https://www.conventionalcommits.org/) format:
        - New features should use: `feat: <description>` or `feat(scope): <description>`
        - Breaking changes should include `!` or a `BREAKING CHANGE:` footer
        - See [commit-instructions.md](https://github.com/alexdresko/collection-merger/blob/main/docs/commit-instructions.md) for details
